name: "Legacy GSM SMS (Test v2)"
description: "Send and receive SMS messages using a GSM modem via pyserial"
version: "0.0.3"
stage: experimental
slug: "legacy_gsm_sms_test_v2"
url: "https://github.com/BigThunderSR/ha-legacy-gsm-sms"
arch:
  - aarch64
  - amd64
uart: true
homeassistant_api: true
init: false
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: HTTP API for sending SMS
options:
  device: "/dev/ttyUSB0"
  baud_speed: "0"
  scan_interval: 30
  log_level: "info"
schema:
  device: str
  baud_speed: list(0|50|75|110|134|150|200|300|600|1200|1800|2400|4800|9600|19200|28800|38400|57600|76800|115200)
  scan_interval: int(10,600)
  log_level: list(debug|info|warning|error)
devices:
  - /dev/ttyUSB[0-9]*
  - /dev/ttyACM[0-9]*
  - /dev/serial/by-id/*
map:
  - share:rw
